### ISSUE TITLE
  Function cufftSetCompatibilityMode was removed in CUDA  9.1

### ISSUE THREAD

**Issue by kandel3** [lebedov/scikit-cuda#248]
So, 

`cufftSetCompatibilityMode ` was removed from CUDA

This seems to break compatibility with scikit-cuda on CUDA 9.2. 

I commented out the reference to `cufftSetCompatibilityMode` and it seems to run fine.

Maybe somebody can take a look and apply the changes?

**Comment by lebedov** [comment]
Fixed - thanks for the report.

**Comment by DrewBarclay** [comment]
@lebedov The problem does not seem fixed (I pulled the latest and tried running it). There are still lines 
```
_libcufft.cufftSetCompatibilityMode.restype = int
_libcufft.cufftSetCompatibilityMode.argtypes = [_types.plan,
ctypes.c_int]
```

in cufft.py which error in CUDA 9.2 for me. Commenting them out (along with your commit) fixed my issue locally.

**Comment by marius10p** [comment]
Having the same error in CUDA 9.2 on Win10.

**Comment by eickenberg** [comment]
yes, those lines are still present (in current master they are here https://github.com/lebedov/scikit-cuda/blob/master/skcuda/cufft.py#L254)

For reference the deprecation notice https://docs.nvidia.com/cuda/cufft/#unique_616614681

I commented the lines for now and something seems to be working, though I need to test that more. I assume this is not the right solution in general though (I'd be happy to make a PR, but don't have enough overview over what needs to be done)

**Comment by lebedov** [comment]
Adding @JWMac888 to issue log.
